  version: '3'
  services:
    db:
      image: postgres:alpine
      environment:
        - POSTGRES_PASSWORD=$DATABASE_PASSWORD
        - POSTGRES_USER=$DATABASE_USER
        - POSTGRES_DB=$DATABASE_NAME
      ports:
        -  "5432:5432"
    vbot:
      environment:
        - DATABASE_HOST=$DATABASE_HOST
        - DATABASE_PORT=$DATABASE_PORT
        - DATABASE_USER=$DATABASE_USER
        - DATABASE_PASSWORD=$DATABASE_PASSWORD
        - DATABASE_NAME=$DATABASE_NAME
        - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      build: .
      command: runserver $LOCAL_IP:$LOCAL_PORT
      depends_on:
        - db